In [21]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_style('whitegrid')

import statistics as st
import scipy as  sp

In [22]:
data= pd.read_csv(r"C:\Users\Amarpreet Singh\Desktop\Innovaccer\mydata.csv")
display(data.head())
data.info()

,aco_num,aco_name,qualscore,qualperfshare,n_ab,n_ben_age_0_64,n_ben_age_65_74,n_ben_age_75_84,n_ben_age_85plus,n_ben_female,n_ben_male,n_ben_race_white,n_ben_race_black,n_ben_race_asian,n_ben_race_hisp,n_ben_race_native,n_ben_race_other,readm_rate_1000,prov_rate_1000,p_em_total,p_em_pcp_vis,p_em_sp_vis,p_nurse_vis,p_fqhc_rhc_vis,n_cah,n_fqhc,n_rhc,n_eta,n_fac_other,n_pcp,n_spec,n_np,n_pa,n_cns,py,aco_state,per_capita_exp_total_py,aim,met_qps,aco1,aco2,aco3,aco4,aco5,aco6,aco7,aco34,aco8,aco35,aco36,aco37,aco38,aco11,aco13,aco14,aco15,aco16,aco17,aco18,aco19,aco20,aco42,aco40,dm_comp,aco27,aco41,aco28,aco30,aco44,aco43,aco12
0,A67373,"Palm Beach Accountable Care Organization, LLC",100.0,50.0,36268,3178,11716,10013,5897,17789,13015,27497,2080,185.0,554.0,12.0,476,164.373717,797.330595,14776.18333,5253.676737,8814.096808,698.069748,10.340039,0,0,0,0,0,118,167,44,0,0,2013,NaN,NaN,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009
1,A38665,Chinese Community Accountable Care Organizatio...,100.0,50.0,13833,1129,4160,4393,1957,7067,4572,834,234,8922.0,102.0,2.0,1545,150.966680,831.345125,15622.09930,9401.238513,6059.281134,122.352734,39.226921,0,0,0,0,0,91,164,15,0,0,2013,NaN,NaN,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009
2,A64796,Summit Health Solutions,100.0,50.0,40595,5508,16680,10728,4420,21051,16285,35819,978,72.0,32.0,21.0,414,130.616074,792.869801,10056.24207,4590.886523,4042.809069,1406.217245,16.329233,0,0,0,0,11,255,200,140,2,1,2013,NaN,NaN,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009
3,A84830,"South Florida Accountable Care Organization,LLC",100.0,50.0,6150,903,2195,2007,1045,3636,2514,4342,471,30.0,1191.0,5.0,111,195.585530,761.496015,13112.59056,5543.483734,6996.111779,544.630619,28.364430,0,0,0,0,0,37,45,3,0,0,2013,NaN,NaN,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009
4,A76261,"Hackensack Physician-Hospital Alliance ACO, LLC",100.0,50.0,16383,1399,6106,4282,2124,8328,5583,12479,598,142.0,295.0,5.0,392,159.579668,824.780059,12513.99002,4770.948069,7212.271299,526.926631,3.844021,0,1,0,0,0,147,377,76,4,0,2013,NaN,NaN,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1849 entries, 0 to 1848
Data columns (total 71 columns):
aco_num                    1849 non-null object
aco_name                   1849 non-null object
qualscore                  1849 non-null float64
qualperfshare              1849 non-null float64
n_ab                       1849 non-null int64
n_ben_age_0_64             1849 non-null int64
n_ben_age_65_74            1849 non-null int64
n_ben_age_75_84            1849 non-null int64
n_ben_age_85plus           1849 non-null int64
n_ben_female               1849 non-null int64
n_ben_male                 1849 non-null int64
n_ben_race_white           1849 non-null int64
n_ben_race_black           1849 non-null int64
n_ben_race_asian           1849 non-null float64
n_ben_race_hisp            1849 non-null float64
n_ben_race_native          1849 non-null float64
n_ben_race_other           1849 non-null int64
readm_rate_1000            1849 non-null float64
prov_rate_1000             1849 non-null float64
p_em_total                 1849 non-null float64
p_em_pcp_vis               1849 non-null float64
p_em_sp_vis                1849 non-null float64
p_nurse_vis                1849 non-null float64
p_fqhc_rhc_vis             1849 non-null float64
n_cah                      1849 non-null int64
n_fqhc                     1849 non-null int64
n_rhc                      1849 non-null int64
n_eta                      1849 non-null int64
n_fac_other                1849 non-null int64
n_pcp                      1849 non-null int64
n_spec                     1849 non-null int64
n_np                       1849 non-null int64
n_pa                       1849 non-null int64
n_cns                      1849 non-null int64
py                         1849 non-null int64
aco_state                  1629 non-null object
per_capita_exp_total_py    1629 non-null float64
aim                        1849 non-null float64
met_qps                    1849 non-null float64
aco1                       1849 non-null float64
aco2                       1849 non-null float64
aco3                       1849 non-null float64
aco4                       1849 non-null float64
aco5                       1849 non-null float64
aco6                       1849 non-null float64
aco7                       1849 non-null float64
aco34                      1849 non-null float64
aco8                       1849 non-null float64
aco35                      1849 non-null float64
aco36                      1849 non-null float64
aco37                      1849 non-null float64
aco38                      1849 non-null float64
aco11                      1849 non-null float64
aco13                      1849 non-null float64
aco14                      1849 non-null float64
aco15                      1849 non-null float64
aco16                      1849 non-null float64
aco17                      1849 non-null float64
aco18                      1849 non-null float64
aco19                      1849 non-null float64
aco20                      1849 non-null float64
aco42                      1849 non-null float64
aco40                      1849 non-null float64
dm_comp                    1849 non-null float64
aco27                      1849 non-null float64
aco41                      1849 non-null float64
aco28                      1849 non-null float64
aco30                      1849 non-null float64
aco44                      1849 non-null float64
aco43                      1849 non-null float64
aco12                      1849 non-null float64
dtypes: float64(47), int64(21), object(3)
memory usage: 1.0+ MB

In [23]:
df = data[data['per_capita_exp_total_py'].notnull()]
display(df.head())
df.info()

,aco_num,aco_name,qualscore,qualperfshare,n_ab,n_ben_age_0_64,n_ben_age_65_74,n_ben_age_75_84,n_ben_age_85plus,n_ben_female,n_ben_male,n_ben_race_white,n_ben_race_black,n_ben_race_asian,n_ben_race_hisp,n_ben_race_native,n_ben_race_other,readm_rate_1000,prov_rate_1000,p_em_total,p_em_pcp_vis,p_em_sp_vis,p_nurse_vis,p_fqhc_rhc_vis,n_cah,n_fqhc,n_rhc,n_eta,n_fac_other,n_pcp,n_spec,n_np,n_pa,n_cns,py,aco_state,per_capita_exp_total_py,aim,met_qps,aco1,aco2,aco3,aco4,aco5,aco6,aco7,aco34,aco8,aco35,aco36,aco37,aco38,aco11,aco13,aco14,aco15,aco16,aco17,aco18,aco19,aco20,aco42,aco40,dm_comp,aco27,aco41,aco28,aco30,aco44,aco43,aco12
220,A67373,"Palm Beach Accountable Care Organization, LLC",91.696429,50.0,34601,3077,13165,11565,6794,20074,14527,31248,1956,198.0,571.0,12.0,616,175.365345,825.782881,14814.26125,5145.037564,8911.748112,735.145354,22.330222,0,0,0,0,0,104,181,35,0,0,2014,Florida,12434.0,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009
221,A38665,Chinese Community Accountable Care Organizatio...,86.584821,50.0,11219,1120,4082,4230,1787,6782,4437,638,198,8769.0,90.0,3.0,1521,169.036335,836.756188,14983.55933,8687.352800,6080.442686,188.050214,27.713626,0,0,0,0,0,91,190,21,0,0,2014,"New York, New Jersey",9594.0,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009
222,A64796,Summit Health Solutions,93.136161,50.0,37174,5364,16886,10524,4400,20915,16259,35572,968,84.0,36.0,19.0,495,151.490640,811.301132,10253.07392,4507.135751,3842.988083,1884.309195,18.640895,0,0,2,0,26,249,208,157,2,1,2014,Tennessee,8305.0,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009
223,A84830,"South Florida Accountable Care Organization,LLC",87.265625,50.0,6850,1010,2453,2166,1221,4138,2712,4733,530,37.0,1439.0,8.0,103,237.935844,777.963738,13106.54224,5686.439507,6769.621080,599.841750,50.639907,0,0,0,0,0,0,0,0,0,0,2014,Florida,18267.0,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009
224,A76261,"Hackensack Physician-Hospital Alliance ACO, LLC",89.430804,50.0,15603,1731,6863,4638,2371,9298,6305,13796,649,202.0,409.0,8.0,539,198.485924,829.903004,12210.38858,4549.512898,7052.998483,603.127130,4.750071,0,1,0,0,5,112,382,73,5,1,2014,"New Jersey, New York",12672.0,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1629 entries, 220 to 1848
Data columns (total 71 columns):
aco_num                    1629 non-null object
aco_name                   1629 non-null object
qualscore                  1629 non-null float64
qualperfshare              1629 non-null float64
n_ab                       1629 non-null int64
n_ben_age_0_64             1629 non-null int64
n_ben_age_65_74            1629 non-null int64
n_ben_age_75_84            1629 non-null int64
n_ben_age_85plus           1629 non-null int64
n_ben_female               1629 non-null int64
n_ben_male                 1629 non-null int64
n_ben_race_white           1629 non-null int64
n_ben_race_black           1629 non-null int64
n_ben_race_asian           1629 non-null float64
n_ben_race_hisp            1629 non-null float64
n_ben_race_native          1629 non-null float64
n_ben_race_other           1629 non-null int64
readm_rate_1000            1629 non-null float64
prov_rate_1000             1629 non-null float64
p_em_total                 1629 non-null float64
p_em_pcp_vis               1629 non-null float64
p_em_sp_vis                1629 non-null float64
p_nurse_vis                1629 non-null float64
p_fqhc_rhc_vis             1629 non-null float64
n_cah                      1629 non-null int64
n_fqhc                     1629 non-null int64
n_rhc                      1629 non-null int64
n_eta                      1629 non-null int64
n_fac_other                1629 non-null int64
n_pcp                      1629 non-null int64
n_spec                     1629 non-null int64
n_np                       1629 non-null int64
n_pa                       1629 non-null int64
n_cns                      1629 non-null int64
py                         1629 non-null int64
aco_state                  1629 non-null object
per_capita_exp_total_py    1629 non-null float64
aim                        1629 non-null float64
met_qps                    1629 non-null float64
aco1                       1629 non-null float64
aco2                       1629 non-null float64
aco3                       1629 non-null float64
aco4                       1629 non-null float64
aco5                       1629 non-null float64
aco6                       1629 non-null float64
aco7                       1629 non-null float64
aco34                      1629 non-null float64
aco8                       1629 non-null float64
aco35                      1629 non-null float64
aco36                      1629 non-null float64
aco37                      1629 non-null float64
aco38                      1629 non-null float64
aco11                      1629 non-null float64
aco13                      1629 non-null float64
aco14                      1629 non-null float64
aco15                      1629 non-null float64
aco16                      1629 non-null float64
aco17                      1629 non-null float64
aco18                      1629 non-null float64
aco19                      1629 non-null float64
aco20                      1629 non-null float64
aco42                      1629 non-null float64
aco40                      1629 non-null float64
dm_comp                    1629 non-null float64
aco27                      1629 non-null float64
aco41                      1629 non-null float64
aco28                      1629 non-null float64
aco30                      1629 non-null float64
aco44                      1629 non-null float64
aco43                      1629 non-null float64
aco12                      1629 non-null float64
dtypes: float64(47), int64(21), object(3)
memory usage: 916.3+ KB

In [26]:
objcols = list(data.select_dtypes(include=['object']).columns)
objcols, len(objcols)

(['aco_num', 'aco_name', 'aco_state'], 3)

# 1. Estimating Regression Coefficients

In [39]:
Indep_vars = df.drop(['aco_num', 'aco_name', 'aco_state', 'per_capita_exp_total_py'], axis=1).columns
Indep_vars, len(Indep_vars)

(Index(['qualscore', 'qualperfshare', 'n_ab', 'n_ben_age_0_64',
        'n_ben_age_65_74', 'n_ben_age_75_84', 'n_ben_age_85plus',
        'n_ben_female', 'n_ben_male', 'n_ben_race_white', 'n_ben_race_black',
        'n_ben_race_asian', 'n_ben_race_hisp', 'n_ben_race_native',
        'n_ben_race_other', 'readm_rate_1000', 'prov_rate_1000', 'p_em_total',
        'p_em_pcp_vis', 'p_em_sp_vis', 'p_nurse_vis', 'p_fqhc_rhc_vis', 'n_cah',
        'n_fqhc', 'n_rhc', 'n_eta', 'n_fac_other', 'n_pcp', 'n_spec', 'n_np',
        'n_pa', 'n_cns', 'py', 'aim', 'met_qps', 'aco1', 'aco2', 'aco3', 'aco4',
        'aco5', 'aco6', 'aco7', 'aco34', 'aco8', 'aco35', 'aco36', 'aco37',
        'aco38', 'aco11', 'aco13', 'aco14', 'aco15', 'aco16', 'aco17', 'aco18',
        'aco19', 'aco20', 'aco42', 'aco40', 'dm_comp', 'aco27', 'aco41',
        'aco28', 'aco30', 'aco44', 'aco43', 'aco12'],
       dtype='object'), 67)

In [30]:
X = df.drop(['aco_num', 'aco_name', 'aco_state', 'per_capita_exp_total_py'], axis=1).values.astype(np.float)
X, X.shape

(array([[9.16964286e+01, 5.00000000e+01, 3.46010000e+04, ...,
         6.73194703e+01, 1.93449153e+00, 7.62360087e+01],
        [8.65848214e+01, 5.00000000e+01, 1.12190000e+04, ...,
         6.73194703e+01, 1.93449153e+00, 7.62360087e+01],
        [9.31361607e+01, 5.00000000e+01, 3.71740000e+04, ...,
         6.73194703e+01, 1.93449153e+00, 7.62360087e+01],
        ...,
        [1.00000000e+02, 5.00000000e+01, 8.73700000e+03, ...,
         7.38100000e+01, 2.67000000e+00, 3.21400000e+01],
        [1.00000000e+02, 7.50000000e+01, 4.06460000e+04, ...,
         6.75400000e+01, 1.52000000e+00, 5.65200000e+01],
        [1.00000000e+02, 7.50000000e+01, 5.99600000e+03, ...,
         5.45500000e+01, 1.92000000e+00, 8.74400000e+01]]), (1629, 67))

In [32]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
X, X.shape

(array([[ 3.71093379e-01, -1.97036483e-01,  9.22974480e-01, ...,
         -2.61718701e-15,  2.07475506e-15, -2.02701112e-15],
        [ 2.13391138e-01, -1.97036483e-01, -3.84501126e-01, ...,
         -2.61718701e-15,  2.07475506e-15, -2.02701112e-15],
        [ 4.15511694e-01, -1.97036483e-01,  1.06685160e+00, ...,
         -2.61718701e-15,  2.07475506e-15, -2.02701112e-15],
        ...,
        [ 6.27273435e-01, -1.97036483e-01, -5.23289701e-01, ...,
          1.19534893e+00,  3.43624636e+00, -3.14488824e+00],
        [ 6.27273435e-01,  5.51421673e+00,  1.26099903e+00, ...,
          4.06145427e-02, -1.93647666e+00, -1.40612826e+00],
        [ 6.27273435e-01,  5.51421673e+00, -6.76561048e-01, ...,
         -2.35172990e+00, -6.77034367e-02,  7.99058727e-01]]), (1629, 67))

In [33]:
y = df['per_capita_exp_total_py'].values
y, y.shape

(array([12434.,  9594.,  8305., ..., 13366., 10951., 13679.]), (1629,))

In [34]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X, y)
reg.score(X, y)

0.7505754707089705

In [36]:
reg.intercept_

10710.371177596287

In [37]:
reg.coef_, len(reg.coef_)

(array([-2.71955231e+02, -1.17032302e+02,  1.42374743e+16, -2.30938193e+15,
        -6.55068966e+15, -3.86590621e+15, -1.82667695e+15, -4.74944328e+06,
        -3.52693892e+06, -4.47942500e+04, -5.75237500e+03, -2.25678125e+03,
        -9.70250000e+02, -7.30000000e+01, -1.78000000e+03,  9.35062500e+02,
        -1.12000000e+02, -1.11705875e+05,  8.75601250e+04,  7.88630000e+04,
         4.21290000e+04,  6.44686562e+04,  9.00000000e+00, -1.49500000e+02,
         4.45000000e+01, -2.06500000e+02,  6.25000000e-02,  1.35000000e+01,
         2.30500000e+02,  6.50000000e+01, -1.20000000e+01, -3.40000000e+01,
         1.32000000e+02,  1.12500000e+00,  1.90000000e+02,  7.13750000e+01,
        -3.44375000e+02,  4.17500000e+01, -8.62500000e+00,  7.05000000e+01,
         4.47500000e+01, -1.15500000e+02, -2.30000000e+01, -3.78875000e+02,
        -8.12500000e+00,  3.80687500e+02, -2.02250000e+02,  3.39125000e+02,
         3.75000000e+01,  3.90000000e+01,  3.75000000e+01,  1.96000000e+02,
        -1.53000000e+02, -5.12500000e+00, -1.50000000e+01, -1.27750000e+02,
        -1.37250000e+02,  1.20000000e+01, -1.11250000e+01,  2.95000000e+02,
         1.52250000e+02, -3.15500000e+02,  8.15000000e+01,  7.92500000e+01,
         4.07500000e+01, -9.23750000e+01, -2.89062500e+01]), 67)

In [46]:
abs_coefs = [abs(x) for x in reg.coef_]
abs_coefs , len(abs_coefs)

([271.9552313239536,
  117.03230203298384,
  1.4237474341479466e+16,
  2309381925817252.5,
  6550689661240490.0,
  3865906209625905.0,
  1826676954261929.5,
  4749443.279320819,
  3526938.9212945374,
  44794.25,
  5752.375,
  2256.78125,
  970.25,
  73.0,
  1780.0,
  935.0625,
  112.0,
  111705.875,
  87560.125,
  78863.0,
  42129.0,
  64468.65625,
  9.0,
  149.5,
  44.5,
  206.5,
  0.0625,
  13.5,
  230.5,
  65.0,
  12.0,
  34.0,
  132.0,
  1.125,
  190.0,
  71.375,
  344.375,
  41.75,
  8.625,
  70.5,
  44.75,
  115.5,
  23.0,
  378.875,
  8.125,
  380.6875,
  202.25,
  339.125,
  37.5,
  39.0,
  37.5,
  196.0,
  153.0,
  5.125,
  15.0,
  127.75,
  137.25,
  12.0,
  11.125,
  295.0,
  152.25,
  315.5,
  81.5,
  79.25,
  40.75,
  92.375,
  28.90625],
 67)

In [47]:
coeffdict = {'Independent_Variables': Indep_vars, 'Regression_Coeffs': abs_coefs}
coeff_df = pd.DataFrame.from_dict(coeffdict)
coeff_df.head()

  Independent_Variables  Regression_Coeffs
0             qualscore       2.719552e+02
1         qualperfshare       1.170323e+02
2                  n_ab       1.423747e+16
3        n_ben_age_0_64       2.309382e+15
4       n_ben_age_65_74       6.550690e+15

In [50]:
coeff_df = coeff_df.sort_values('Regression_Coeffs', ascending=False)

In [51]:
coeff_df

   Independent_Variables  Regression_Coeffs
2                   n_ab       1.423747e+16
4        n_ben_age_65_74       6.550690e+15
5        n_ben_age_75_84       3.865906e+15
3         n_ben_age_0_64       2.309382e+15
6       n_ben_age_85plus       1.826677e+15
7           n_ben_female       4.749443e+06
8             n_ben_male       3.526939e+06
17            p_em_total       1.117059e+05
18          p_em_pcp_vis       8.756012e+04
19           p_em_sp_vis       7.886300e+04
21        p_fqhc_rhc_vis       6.446866e+04
9       n_ben_race_white       4.479425e+04
20           p_nurse_vis       4.212900e+04
10      n_ben_race_black       5.752375e+03
11      n_ben_race_asian       2.256781e+03
14      n_ben_race_other       1.780000e+03
12       n_ben_race_hisp       9.702500e+02
15       readm_rate_1000       9.350625e+02
45                 aco36       3.806875e+02
43                  aco8       3.788750e+02
36                  aco2       3.443750e+02
47                 aco38       3.391250e+02
61                 aco41       3.155000e+02
59               dm_comp       2.950000e+02
0              qualscore       2.719552e+02
28                n_spec       2.305000e+02
25                 n_eta       2.065000e+02
46                 aco37       2.022500e+02
51                 aco15       1.960000e+02
34               met_qps       1.900000e+02
..                   ...                ...
41                  aco7       1.155000e+02
16        prov_rate_1000       1.120000e+02
65                 aco43       9.237500e+01
62                 aco28       8.150000e+01
63                 aco30       7.925000e+01
13     n_ben_race_native       7.300000e+01
35                  aco1       7.137500e+01
39                  aco5       7.050000e+01
29                  n_np       6.500000e+01
40                  aco6       4.475000e+01
24                 n_rhc       4.450000e+01
37                  aco3       4.175000e+01
64                 aco44       4.075000e+01
49                 aco13       3.900000e+01
48                 aco11       3.750000e+01
50                 aco14       3.750000e+01
31                 n_cns       3.400000e+01
66                 aco12       2.890625e+01
42                 aco34       2.300000e+01
54                 aco18       1.500000e+01
27                 n_pcp       1.350000e+01
30                  n_pa       1.200000e+01
57                 aco42       1.200000e+01
58                 aco40       1.112500e+01
22                 n_cah       9.000000e+00
38                  aco4       8.625000e+00
44                 aco35       8.125000e+00
53                 aco17       5.125000e+00
33                   aim       1.125000e+00
26           n_fac_other       6.250000e-02

[67 rows x 2 columns]

In [52]:
Imp_vars = coeff_df['Independent_Variables'].values
Imp_vars

array(['n_ab', 'n_ben_age_65_74', 'n_ben_age_75_84', 'n_ben_age_0_64',
       'n_ben_age_85plus', 'n_ben_female', 'n_ben_male', 'p_em_total',
       'p_em_pcp_vis', 'p_em_sp_vis', 'p_fqhc_rhc_vis',
       'n_ben_race_white', 'p_nurse_vis', 'n_ben_race_black',
       'n_ben_race_asian', 'n_ben_race_other', 'n_ben_race_hisp',
       'readm_rate_1000', 'aco36', 'aco8', 'aco2', 'aco38', 'aco41',
       'dm_comp', 'qualscore', 'n_spec', 'n_eta', 'aco37', 'aco15',
       'met_qps', 'aco16', 'aco27', 'n_fqhc', 'aco20', 'py', 'aco19',
       'qualperfshare', 'aco7', 'prov_rate_1000', 'aco43', 'aco28',
       'aco30', 'n_ben_race_native', 'aco1', 'aco5', 'n_np', 'aco6',
       'n_rhc', 'aco3', 'aco44', 'aco13', 'aco11', 'aco14', 'n_cns',
       'aco12', 'aco34', 'aco18', 'n_pcp', 'n_pa', 'aco42', 'aco40',
       'n_cah', 'aco4', 'aco35', 'aco17', 'aim', 'n_fac_other'],
      dtype=object)

**So, it's shown by above mathematics that most important feature for 'per_capita_exp_total_py' as dependent variable in the regression analysis is 'n_ab' and the least important is 'n_fac_other' as they are arranged according to their decreasing value of regression coefficients hence decreasing measure of their importance.**

In [55]:
# #or
# lm = LinearRegression()
# lm.fit(X,y)
# params = np.append(lm.intercept_,lm.coef_)
# predictions = lm.predict(X)

# newX = pd.DataFrame({"Constant":np.ones(len(X))}).join(pd.DataFrame(X))
# MSE = (sum((y-predictions)**2))/(len(newX)-len(newX.columns))

# # Note if you don't want to use a DataFrame replace the two lines above with
# # newX = np.append(np.ones((len(X),1)), X, axis=1)
# # MSE = (sum((y-predictions)**2))/(len(newX)-len(newX[0]))

# var_b = MSE*(np.linalg.inv(np.dot(newX.T,newX)).diagonal())
# sd_b = np.sqrt(var_b)
# ts_b = params/ sd_b

# p_values =[2*(1-stats.t.cdf(np.abs(i),(len(newX)-1))) for i in ts_b]

# sd_b = np.round(sd_b,3)
# ts_b = np.round(ts_b,3)
# p_values = np.round(p_values,3)
# params = np.round(params,4)

# myDF3 = pd.DataFrame()
# myDF3["Coefficients"],myDF3["Standard Errors"],myDF3["t values"],myDF3["Probabilites"] = [params,sd_b,ts_b,p_values]
# print(myDF3)

In [53]:
import statsmodels.api as sm
from scipy import stats

X2 = sm.add_constant(X)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.740
Method:                 Least Squares   F-statistic:                     71.32
Date:                Sat, 24 Nov 2018   Prob (F-statistic):               0.00
Time:                        15:42:06   Log-Likelihood:                -13994.
No. Observations:                1629   AIC:                         2.812e+04
Df Residuals:                    1562   BIC:                         2.848e+04
Df Model:                          66
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.071e+04     32.936    325.168      0.000    1.06e+04    1.08e+04
x1          -271.9552    185.543     -1.466      0.143    -635.895      91.984
x2          -104.2455     36.767     -2.835      0.005    -176.364     -32.127
x3          2.078e+06   1.95e+06      1.068      0.286   -1.74e+06    5.89e+06
x4          1.026e+06   9.62e+05      1.067      0.286    -8.6e+05    2.91e+06
x5          2.915e+06   2.73e+06      1.069      0.285   -2.44e+06    8.26e+06
x6          1.717e+06   1.61e+06      1.066      0.286   -1.44e+06    4.87e+06
x7           8.15e+05   7.61e+05      1.072      0.284   -6.77e+05    2.31e+06
x8         -4.802e+06   4.52e+06     -1.062      0.288   -1.37e+07    4.07e+06
x9         -3.567e+06   3.36e+06     -1.062      0.288   -1.02e+07    3.02e+06
x10        -4.281e+04   1.08e+05     -0.395      0.693   -2.56e+05     1.7e+05
x11        -5497.9710   1.45e+04     -0.380      0.704   -3.39e+04    2.29e+04
x12        -2160.1043   5189.568     -0.416      0.677   -1.23e+04    8019.149
x13         -910.3460   2977.369     -0.306      0.760   -6750.407    4929.715
x14          -59.8948    512.193     -0.117      0.907   -1064.554     944.764
x15        -1683.1527   4038.470     -0.417      0.677   -9604.547    6238.242
x16          944.8806     52.148     18.119      0.000     842.594    1047.167
x17         -107.1554     50.264     -2.132      0.033    -205.748      -8.562
x18        -1.126e+05   1.04e+05     -1.087      0.277   -3.16e+05    9.05e+04
x19         8.822e+04   8.04e+04      1.098      0.272   -6.94e+04    2.46e+05
x20         7.945e+04   7.24e+04      1.097      0.273   -6.26e+04    2.21e+05
x21         4.245e+04   3.84e+04      1.106      0.269   -3.29e+04    1.18e+05
x22         6.495e+04   5.91e+04      1.099      0.272   -5.09e+04    1.81e+05
x23            2.5358     62.597      0.041      0.968    -120.247     125.318
x24         -159.0533     53.690     -2.962      0.003    -264.365     -53.741
x25           56.8881     69.736      0.816      0.415     -79.899     193.675
x26         -211.8862     39.430     -5.374      0.000    -289.227    -134.546
x27           -9.4734     38.277     -0.247      0.805     -84.554      65.607
x28           -6.5769    106.627     -0.062      0.951    -215.724     202.570
x29          233.0258     76.678      3.039      0.002      82.624     383.428
x30           68.2133    100.972      0.676      0.499    -129.842     266.268
x31           -7.4061     55.110     -0.134      0.893    -115.504     100.691
x32          -34.3210     44.365     -0.774      0.439    -121.343      52.701
x33          122.4698     70.344      1.741      0.082     -15.508     260.448
x34            6.1268     66.298      0.092      0.926    -123.916     136.169
x35          189.0383    179.429      1.054      0.292    -162.909     540.986
x36           63.8458     45.298      1.409      0.159     -25.005     152.697
x37         -348.8245     81.207     -4.295      0.000    -508.111    -189.538
x38           40.5387     77.274      0.525      0.600    -111.034     192.111
x39           -0.7718     37.833     -0.020      0.984     -74.981      73.437
x40           69.1358     43.832      1.577      0.115     -16.839     155.111
x41           46.6105     40.276      1.157      0.247     -32.390     125.611
x42         -115.8624     47.073     -2.461      0.014    -208.195     -23.530
x43          -29.2991     40.167     -0.729      0.466    -108.086      49.488
x44         -366.2930     58.159     -6.298      0.000    -480.370    -252.216
x45          -11.2862     45.461     -0.248      0.804    -100.457      77.884
x46          371.5705     88.235      4.211      0.000     198.498     544.643
x47         -210.1845    110.621     -1.900      0.058    -427.166       6.797
x48          348.8678    125.931      2.770      0.006     101.855     595.880
x49           47.0076     40.700      1.155      0.248     -32.825     126.840
x50           38.5423     56.863      0.678      0.498     -72.994     150.079
x51           30.3542     55.612      0.546      0.585     -78.727     139.436
x52          196.6062     72.510      2.711      0.007      54.378     338.834
x53         -148.1361     44.976     -3.294      0.001    -236.355     -59.917
x54          -13.9790     42.487     -0.329      0.742     -97.317      69.359
x55           -9.5635     58.934     -0.162      0.871    -125.162     106.035
x56         -119.8636     69.798     -1.717      0.086    -256.772      17.045
x57         -144.5547     60.543     -2.388      0.017    -263.309     -25.800
x58            8.7383     44.074      0.198      0.843     -77.712      95.189
x59          -13.5727     35.039     -0.387      0.699     -82.302      55.157
x60          207.2077    264.095      0.785      0.433    -310.811     725.226
x61          137.6925     66.788      2.062      0.039       6.688     268.697
x62         -226.5161    244.029     -0.928      0.353    -705.175     252.143
x63           88.9442     45.386      1.960      0.050      -0.080     177.969
x64           83.2639     48.833      1.705      0.088     -12.522     179.050
x65           38.7144     35.033      1.105      0.269     -30.003     107.432
x66          -85.2333     38.815     -2.196      0.028    -161.367      -9.099
x67          -27.3797     35.582     -0.769      0.442     -97.173      42.414
==============================================================================
Omnibus:                      594.779   Durbin-Watson:                   2.004
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8287.880
Skew:                           1.311   Prob(JB):                         0.00
Kurtosis:                      13.735   Cond. No.                     2.26e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.92e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

# 2. R-squared when each variable is added to a model that already contains all of the other variables:
the associated change in R-squared represents the improvement in the goodness-of-fit that is due solely to that last variable 
after all of the other variables have been accounted for.

**Forward selection**:
We start with a null model (no features), we then fit 67 simple linear regressions and add to the null model the variable that results in the lowest RSS.

In [56]:
Indep_vars

Index(['qualscore', 'qualperfshare', 'n_ab', 'n_ben_age_0_64',
       'n_ben_age_65_74', 'n_ben_age_75_84', 'n_ben_age_85plus',
       'n_ben_female', 'n_ben_male', 'n_ben_race_white', 'n_ben_race_black',
       'n_ben_race_asian', 'n_ben_race_hisp', 'n_ben_race_native',
       'n_ben_race_other', 'readm_rate_1000', 'prov_rate_1000', 'p_em_total',
       'p_em_pcp_vis', 'p_em_sp_vis', 'p_nurse_vis', 'p_fqhc_rhc_vis', 'n_cah',
       'n_fqhc', 'n_rhc', 'n_eta', 'n_fac_other', 'n_pcp', 'n_spec', 'n_np',
       'n_pa', 'n_cns', 'py', 'aim', 'met_qps', 'aco1', 'aco2', 'aco3', 'aco4',
       'aco5', 'aco6', 'aco7', 'aco34', 'aco8', 'aco35', 'aco36', 'aco37',
       'aco38', 'aco11', 'aco13', 'aco14', 'aco15', 'aco16', 'aco17', 'aco18',
       'aco19', 'aco20', 'aco42', 'aco40', 'dm_comp', 'aco27', 'aco41',
       'aco28', 'aco30', 'aco44', 'aco43', 'aco12'],
      dtype='object')

In [73]:
len(data)

1629

In [70]:
data = df.loc[:, list(Indep_vars)+['per_capita_exp_total_py']]
data.head()

,qualscore,qualperfshare,n_ab,n_ben_age_0_64,n_ben_age_65_74,n_ben_age_75_84,n_ben_age_85plus,n_ben_female,n_ben_male,n_ben_race_white,n_ben_race_black,n_ben_race_asian,n_ben_race_hisp,n_ben_race_native,n_ben_race_other,readm_rate_1000,prov_rate_1000,p_em_total,p_em_pcp_vis,p_em_sp_vis,p_nurse_vis,p_fqhc_rhc_vis,n_cah,n_fqhc,n_rhc,n_eta,n_fac_other,n_pcp,n_spec,n_np,n_pa,n_cns,py,aim,met_qps,aco1,aco2,aco3,aco4,aco5,aco6,aco7,aco34,aco8,aco35,aco36,aco37,aco38,aco11,aco13,aco14,aco15,aco16,aco17,aco18,aco19,aco20,aco42,aco40,dm_comp,aco27,aco41,aco28,aco30,aco44,aco43,aco12,per_capita_exp_total_py
220,91.696429,50.0,34601,3077,13165,11565,6794,20074,14527,31248,1956,198.0,571.0,12.0,616,175.365345,825.782881,14814.26125,5145.037564,8911.748112,735.145354,22.330222,0,0,0,0,0,104,181,35,0,0,2014,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009,12434.0
221,86.584821,50.0,11219,1120,4082,4230,1787,6782,4437,638,198,8769.0,90.0,3.0,1521,169.036335,836.756188,14983.55933,8687.352800,6080.442686,188.050214,27.713626,0,0,0,0,0,91,190,21,0,0,2014,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009,9594.0
222,93.136161,50.0,37174,5364,16886,10524,4400,20915,16259,35572,968,84.0,36.0,19.0,495,151.490640,811.301132,10253.07392,4507.135751,3842.988083,1884.309195,18.640895,0,0,2,0,26,249,208,157,2,1,2014,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009,8305.0
223,87.265625,50.0,6850,1010,2453,2166,1221,4138,2712,4733,530,37.0,1439.0,8.0,103,237.935844,777.963738,13106.54224,5686.439507,6769.621080,599.841750,50.639907,0,0,0,0,0,0,0,0,0,0,2014,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009,18267.0
224,89.430804,50.0,15603,1731,6863,4638,2371,9298,6305,13796,649,202.0,409.0,8.0,539,198.485924,829.903004,12210.38858,4549.512898,7052.998483,603.127130,4.750071,0,1,0,0,5,112,382,73,5,1,2014,-1.0,1.0,80.047763,92.724308,91.96299,83.458616,61.009147,75.466412,72.206622,26.979623,14.859779,18.31917,53.592754,77.291847,60.826128,87.113108,69.421184,70.496615,71.137542,72.481285,90.735196,57.980961,63.171823,68.953658,78.840045,7.347293,42.05067,17.463598,47.779777,71.121911,85.982447,67.31947,1.934492,76.236009,12672.0

In [76]:
X1 = [0 for i in range(0,1629)]
len(X1)

1629

In [57]:
X2 = sm.add_constant(X)
# est = sm.OLS(y, X2)
# est2 = est.fit()
# print(est2.summary())

In [72]:
def evaluateModel(model):
    print("RSS = ", ((data['per_capita_exp_total_py'] - model.predict())**2).sum())
    print("R2 = ", model.rsquared)

In [80]:
model1 = sm.OLS(y, data['qualscore']).fit()
display(evaluateModel(model1))
model1.summary().tables[1]

RSS =  37798408635.37645
R2 =  0.8090237228147363

None

**In the same way we keep on adding new features and see if RSS is being sufficiently reduced.** 
(Didn't have much time, apologies for not finishing this segment)